language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t shidhu23/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true shidhu23/react-test npm test

after_success:
    - docker build -t shidhu23/multi-client ./client
    - docker build -t shidhu23/multi-nginx ./nginx
    - docker build -t shidhu23/multi-server ./server
    - docker build -t shidhu23/multi-worker ./worker
    #to login to docker-hub to and push our image 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    - docker push shidhu23/multi-client
    - docker push shidhu23/multi-nginx
    - docker push shidhu23/multi-server
    - docker push shidhu23/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-152184266202
    buket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY